In [32]:
n=(input('enter a number'))
c=len(n)
n=int(n)
l=c//2
b=10**l
p1=n//b
p2=n%b
if p1>p2:
    print(p1-p2)
else:
    print(p2-p1)

    
   

enter a number12345
78


In [30]:
5//2

2

In [26]:
l=[1,1,2,3,45,3,34,43]
b=[]
for i in l:
    if i not in b:
        b.append(i)
print(b)
    
        



[1, 2, 3, 45, 34, 43]


In [28]:
l=[1,1,2,3,45,3,34,43]
b=[]
for i in l:
    if l.count(i) is 1:
        b.append(i)
print(b)
    

[2, 45, 34, 43]


In [34]:
l=[1,1,2,3,45,3,34,43]
b=[]
for i in l:
    if l.count(i) is not 1:
        if i not in b:
            b.append(i)
print(b)

[1, 3]


In [47]:
n=input('enter name')
d={}
for i in n:
    d.update({i:ord(i)})
print(d)
    

enter namestar
{'s': 115, 't': 116, 'a': 97, 'r': 114}


In [49]:
n=input('enter name')
d={}
for i in n:
    d[i]=ord(i)
print(d)
    

enter namestar
{'s': 115, 't': 116, 'a': 97, 'r': 114}


In [55]:
s=input('enter a string')
char_freq={}
for i in s:
    if i in char_freq:
        char_freq[i] +=1
    else:
        char_freq[i] = 1
print(char_freq)

enter a stringcoffee
{'c': 1, 'o': 1, 'f': 2, 'e': 2}


In [19]:
n=(input('enter a number'))
c=len(n)
n=int(n)
l=int(input('enter count'))
a=10**(c-l)
b=10**l
p1=n//a
p2=n%b
if p1>p2:
    print(p1-p2)
else:
    print(p2-p1)

    

enter a number1234567
enter count3
444


In [23]:
n=int(input('enter number'))
s=0
for i in range(1,n):
    if n%i==0:
        s=s+i
if s<n:
    print("deficient number")
else:
    print('abundant numbers.')
    

enter number12
abundant numbers.


In [21]:
1+2+3+4+6

16

In [24]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
l=[1,2,3,4]
a=np.array(l)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.dtype)
print(np.append(a,[5,6,7]))
print(a.nbytes)

<class 'numpy.ndarray'>
1
(4,)
int32
[1 2 3 4 5 6 7]
16


In [47]:
#2D array
p=[1,2,3]
q=[4,5,6]
h=np.array([p,q])
print(h)

[[1 2 3]
 [4 5 6]]


In [49]:
h[0,2]

3

In [50]:
h[1]

array([4, 5, 6])

In [52]:
h[:,2]

array([3, 6])

In [55]:
h[1,1:3]

array([5, 6])

In [57]:
a=[1,2,3]
b=[4,5,6]
c=[7,4,2]
b=np.array([[a,b],[[3,4,5],[5,5,3]]])
print(b)
print(b.shape)

[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [5 5 3]]]
(2, 2, 3)


In [58]:
b[1,0,2]

5

In [59]:
b[:,1,1]

array([5, 5])

In [61]:
b[:,:,0]

array([[1, 4],
       [3, 5]])

In [62]:
t=np.arange(10)
print(t)
print(type(t))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [63]:
t1=np.arange(4,10)
print(t1)

[4 5 6 7 8 9]


In [65]:
t2=np.arange(0,11,2)
print(t2)

[ 0  2  4  6  8 10]


In [66]:
a=np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
b=np.arange(20,40,2)
print(b)

[20 22 24 26 28 30 32 34 36 38]


In [70]:
b=np.arange(12).reshape(1,2,6)
print(b)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]]


In [4]:
b=np.arange(12).reshape(3,2,2,2)
print(b)

ValueError: cannot reshape array of size 12 into shape (3,2,2,2)

In [74]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [78]:
o=np.linspace(1,10,5).reshape(5,1)
o

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [79]:
o=np.logspace(1,10,5).reshape(5,1)
o

array([[1.00000000e+01],
       [1.77827941e+03],
       [3.16227766e+05],
       [5.62341325e+07],
       [1.00000000e+10]])

In [83]:
v=np.zeros((4,5),dtype=int)
v

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [87]:
k=np.ones((2,3,5),dtype=int)
k

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [88]:
g=np.full((3,4),5)
g

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])