In [15]:
n=int(input('enter number'))
m=int(input('enter number'))
c=n+m
for i in range(c+1,c+10):
    co=0
    for j in range(1,c+10):
        if i%j==0:
            co=co+1
    if co==2:
        print(i-c)
        break
        

    

enter number4
enter number3
4


In [12]:
11+13


24

In [ ]:
if c%i==0:
        co=co+1
        print(co)
        if co==2:
            print(i)
            break

In [16]:
import numpy as np
r=np.random.random()
r

0.3254932128306224

In [17]:
r=np.random.random((2,3))#normal 
r

array([[0.77480803, 0.34542902, 0.47771004],
       [0.71230571, 0.29718667, 0.53870361]])

In [18]:
r=np.random.rand()#
r

0.4739982842463387

In [19]:
r=np.random.randn()
r

-0.019163017714952248

In [20]:
r=np.random.randn(3,4)
r

array([[-0.37213256,  0.81458943, -0.42860708, -0.71716259],
       [-1.36119956, -0.45675895,  0.74525696,  0.61593178],
       [-1.50334756, -0.23618028,  1.10157334,  0.24579761]])

In [34]:
r=np.random.randint(5)
r

2

In [37]:
r=np.random.randint(1,15,3)
r

array([[ 1, 14,  5],
       [ 2,  7,  9],
       [13,  6,  1]])

In [39]:
r=np.random.randint(1,15,size=(5,5))
r

array([[ 7, 12, 11, 13,  5],
       [ 5,  5,  2, 12, 11],
       [ 5,  8,  6,  3,  8],
       [ 2,  6,  3,  6,  7],
       [10, 10, 13,  2,  2]])

In [45]:
r=np.random.randint(100000,999999)
r

358042

In [46]:
print(dir(np.random))

['Lock', 'RandomState', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']


In [48]:
l=[1,2,3,45,5]
r=np.random.shuffle(l)
print(r)

None


In [50]:
help(np.char)

Help on module numpy.core.defchararray in numpy.core:

NAME
    numpy.core.defchararray

DESCRIPTION
    This module contains a set of functions for vectorized string
    operations and methods.
    
    .. note::
       The `chararray` class exists for backwards compatibility with
       Numarray, it is not recommended for new development. Starting from numpy
       1.4, if one needs arrays of strings, it is recommended to use arrays of
       `dtype` `object_`, `string_` or `unicode_`, and use the free functions
       in the `numpy.char` module for fast vectorized string operations.
    
    Some methods will only be available if the corresponding string method is
    available in your version of Python.
    
    The preferred alias for `defchararray` is `numpy.char`.

CLASSES
    numpy.ndarray(builtins.object)
        numpy.chararray
    
    class chararray(ndarray)
     |  chararray(shape, itemsize=1, unicode=False, buffer=None, offset=0, strides=None, order='C')
     |  
     | 

In [51]:
print(dir(np.char))

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_binary_op_dispatcher', '_bytes', '_center_dispatcher', '_clean_args', '_code_dispatcher', '_count_dispatcher', '_endswith_dispatcher', '_expandtabs_dispatcher', '_get_num_chars', '_globalvar', '_join_dispatcher', '_just_dispatcher', '_len', '_mod_dispatcher', '_multiply_dispatcher', '_partition_dispatcher', '_replace_dispatcher', '_split_dispatcher', '_splitlines_dispatcher', '_startswith_dispatcher', '_strip_dispatcher', '_to_string_or_unicode_array', '_translate_dispatcher', '_unary_op_dispatcher', '_unicode', '_use_unicode', '_vec_string', '_zfill_dispatcher', 'absolute_import', 'add', 'array', 'array_function_dispatch', 'asarray', 'asbytes', 'bool_', 'capitalize', 'center', 'character', 'chararray', 'compare_chararrays', 'count', 'decode', 'division', 'encode', 'endswith', 'equal', 'expandtabs', 'find', 'functools', 'greater', 'greater_equal', 'index', 'integer', 

In [59]:
help(np.char.lower)

Help on function lower:

lower(a)
    Return an array with the elements converted to lowercase.
    
    Call `str.lower` element-wise.
    
    For 8-bit strings, this method is locale-dependent.
    
    Parameters
    ----------
    a : array_like, {str, unicode}
        Input array.
    
    Returns
    -------
    out : ndarray, {str, unicode}
        Output array of str or unicode, depending on input type
    
    See also
    --------
    str.lower
    
    Examples
    --------
    >>> c = np.array(['A1B C', '1BCA', 'BCA1']); c
    array(['A1B C', '1BCA', 'BCA1'],
          dtype='|S5')
    >>> np.char.lower(c)
    array(['a1b c', '1bca', 'bca1'],
          dtype='|S5')



In [52]:
n=['RAmya','BinDHU','SUShma']
n=np.array(n)
n

array(['RAmya', 'BinDHU', 'SUShma'], dtype='<U6')

In [54]:
np.char.lower(n)

array(['ramya', 'bindhu', 'sushma'], dtype='<U6')

In [55]:
np.char.upper(n)

array(['RAMYA', 'BINDHU', 'SUSHMA'], dtype='<U6')

In [56]:
np.char.split(n)

array([list(['RAmya']), list(['BinDHU']), list(['SUShma'])], dtype=object)

In [57]:
np.char.swapcase(n)

array(['raMYA', 'bINdhu', 'susHMA'], dtype='<U6')

In [60]:
np.char.title(n)

array(['Ramya', 'Bindhu', 'Sushma'], dtype='<U6')

In [62]:
np.char.endswith(n,'a')

array([ True, False,  True])

In [63]:
np.char.startswith(n,'s')

array([False, False, False])

In [74]:
a=np.char.add(['ko','cap','se'],['rea','tail','oul'])
b=np.char.add(a,['bi','ra','su'])
b

array(['koreabi', 'captailra', 'seoulsu'], dtype='<U9')

In [77]:
p=['stella','bindhu','ramya','sushma']
q=['6','5','2','3']
r=['cse','ml','it','ece']
l=np.char.add(p,q)
n=np.char.add(l,r)
n=np.char.title(n)
print(n)

['Stella6Cse' 'Bindhu5Ml' 'Ramya2It' 'Sushma3Ece']


In [78]:
np.sort(n)

array(['Bindhu5Ml', 'Ramya2It', 'Stella6Cse', 'Sushma3Ece'], dtype='<U10')

In [80]:
np.char.capitalize(n)#converts only 1st char to upper and does not bother about the remaining characters

array(['Stella6cse', 'Bindhu5ml', 'Ramya2it', 'Sushma3ece'], dtype='<U10')

In [88]:
p=[5,3,2]
q=[4,8,5]
h=np.array([p,q])
print(h)

[[5 3 2]
 [4 8 5]]


In [89]:
np.sort(h)

array([[2, 3, 5],
       [4, 5, 8]])

In [90]:
np.sort(h,0)

array([[4, 3, 2],
       [5, 8, 5]])

In [91]:
np.argmin(h)#returns the index of min value in the entire matrix

2

In [92]:
np.argmax(h)#returns the index of max value in the entire matrix

4

In [93]:
p=[5,3,0]
q=[4,0,5]
h=np.array([p,q])
h.nonzero()#gives the index of non zero elements

(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 2], dtype=int64))

In [94]:
h>3

array([[ True, False, False],
       [ True, False,  True]])

In [95]:
h[h>3]

array([5, 4, 5])

In [96]:
np.hstack(h)

array([5, 3, 0, 4, 0, 5])

In [110]:
p=[5,3,1]
q=[4,5,5]
h=np.array([p,q])
p1=[8,3,5]
q1=[4,6,5]
r=[1,2,3]
h1=np.array([p1,q1,r])
print(h)
print(h1)

[[5 3 1]
 [4 5 5]]
[[8 3 5]
 [4 6 5]
 [1 2 3]]


In [103]:
h1+h

array([[13,  6,  6],
       [ 8, 11, 10]])

In [113]:
h@h1#matrix multiplication

array([[53, 35, 43],
       [57, 52, 60]])

In [105]:
np.transpose(h)

array([[5, 4],
       [3, 5],
       [1, 5]])

In [106]:
h-h1

array([[-3,  0, -4],
       [ 0, -1,  0]])

In [116]:
np.hstack(h1)

array([8, 3, 5, 4, 6, 5, 1, 2, 3])

In [117]:
np.vstack(h1)

array([[8, 3, 5],
       [4, 6, 5],
       [1, 2, 3]])